/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainMenuRu?: Array<{
    label?: string;
    link?: PageReference | HomePageReference;
    _key: string;
  }>;
  mainMenuUa?: Array<{
    label?: string;
    link?: PageReference | HomePageReference;
    _key: string;
  }>;
  footerText?: {
    ru?: string;
    ua?: string;
  };
  contact?: {
    address?: string;
    phone?: string;
    website?: string;
    mapLocation?: Geopoint;
  };
  seo?: {
    title?: {
      ua?: string;
      ru?: string;
    };
    description?: {
      ua?: string;
      ru?: string;
    };
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    ogImageAlt?: {
      ua?: string;
      ru?: string;
    };
    canonicalBaseUrl?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: HomePageReference | PageReference;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug: Slug;
  body?: BlockContent;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  introText?: BlockContent;
  meetingSection?: {
    sectionTitle?: string;
    time?: string;
    languages?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | PageReference
  | HomePageReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Geopoint
  | BlockContent
  | TranslationMetadata
  | InternationalizedArrayReference
  | InternationalizedArrayReferenceValue
  | Page
  | Slug
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: ../web/src/queries.ts
// Variable: siteSettingsQuery
// Query: *[_id == "siteSettings"][0]{  logo,  mainMenuRu[]{    label,    "link": link->{ _type, "slug": slug.current }  },  mainMenuUa[]{    label,    "link": link->{ _type, "slug": slug.current }  },  footerText,  "contact": coalesce(contact, footerContact),  seo{    title,    description,    ogImage,    ogImageAlt,    canonicalBaseUrl  }}
export type SiteSettingsQueryResult =
  | {
      logo: null;
      mainMenuRu: null;
      mainMenuUa: null;
      footerText: null;
      contact: null;
      seo: null;
    }
  | {
      logo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      mainMenuRu: Array<{
        label: string | null;
        link:
          | {
              _type: "homePage";
              slug: null;
            }
          | {
              _type: "page";
              slug: string;
            }
          | null;
      }> | null;
      mainMenuUa: Array<{
        label: string | null;
        link:
          | {
              _type: "homePage";
              slug: null;
            }
          | {
              _type: "page";
              slug: string;
            }
          | null;
      }> | null;
      footerText: {
        ru?: string;
        ua?: string;
      } | null;
      contact: {
        address?: string;
        phone?: string;
        website?: string;
        mapLocation?: Geopoint;
      } | null;
      seo: {
        title: {
          ua?: string;
          ru?: string;
        } | null;
        description: {
          ua?: string;
          ru?: string;
        } | null;
        ogImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        ogImageAlt: {
          ua?: string;
          ru?: string;
        } | null;
        canonicalBaseUrl: string | null;
      } | null;
    }
  | null;

// Source: ../web/src/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage" && language == $locale][0]{  title,  introText,  language,  meetingSection{    sectionTitle,    time,    languages  }}
export type HomePageQueryResult = {
  title: string | null;
  introText: BlockContent | null;
  language: string | null;
  meetingSection: {
    sectionTitle: string | null;
    time: string | null;
    languages: string | null;
  } | null;
} | null;

// Source: ../web/src/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && language == $locale && slug.current == $slug][0]{  title,  body,  slug}
export type PageBySlugQueryResult = {
  title: string | null;
  body: BlockContent | null;
  slug: Slug;
} | null;

// Source: ../web/src/queries.ts
// Variable: allPageSlugsQuery
// Query: *[_type == "page" && defined(slug.current)]{  "locale": language,  "slug": slug.current}
export type AllPageSlugsQueryResult = Array<{
  locale: string | null;
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_id == "siteSettings"][0]{\n  logo,\n  mainMenuRu[]{\n    label,\n    "link": link->{ _type, "slug": slug.current }\n  },\n  mainMenuUa[]{\n    label,\n    "link": link->{ _type, "slug": slug.current }\n  },\n  footerText,\n  "contact": coalesce(contact, footerContact),\n  seo{\n    title,\n    description,\n    ogImage,\n    ogImageAlt,\n    canonicalBaseUrl\n  }\n}': SiteSettingsQueryResult;
    '*[_type == "homePage" && language == $locale][0]{\n  title,\n  introText,\n  language,\n  meetingSection{\n    sectionTitle,\n    time,\n    languages\n  }\n}': HomePageQueryResult;
    '*[_type == "page" && language == $locale && slug.current == $slug][0]{\n  title,\n  body,\n  slug\n}': PageBySlugQueryResult;
    '*[_type == "page" && defined(slug.current)]{\n  "locale": language,\n  "slug": slug.current\n}': AllPageSlugsQueryResult;
  }
}
